name: Custom jjmerelo/alpine-raku
description: Extend jjmerelo/alpine-raku with more packages

inputs:
  script:
    description: Bash script to run
    required: true

runs:
  using: docker
  image: ./Dockerfile
  entrypoint: bash
  args:
    - -c
    - ${{ inputs.script }}
