name: CI (push)

on:
  push:
    branches: ['**']
    paths:
      - .github/**
      - ./**
  workflow_dispatch:
  repository_dispatch:

jobs:
  commit-check:
    name: Commit check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run static analysis tool
        uses: ./.github/actions/alpine-raku
        with:
          script: |
            # fail on first error
            #set -Eeuo pipefail

            ls /home/raku/.raku/bin
            file /home/raku/.raku/bin/vic2-companion
            command -v vic2-companion

            # run static analysis
            vic2-companion --color=always --heartbeat --whitelist --remarks=opinion "${scaffolding[@]}" "${commit_files[@]}"
