name: CI (push)

on:
  push:
    branches: ['**']
    paths:
      - .github/**
      - ./**
  workflow_dispatch:
  repository_dispatch:

jobs:
  commit-check:
    name: Commit check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: moretrim/ccHFM
          fetch-depth: 2

      - name: Run static analysis tool
        uses: ./.github/actions/alpine-raku
        with:
          script: |
            # fail on first error
            set -Eeuo pipefail

            # compute difference
            readarray -d "" commit_files < <(git diff-tree -z --no-commit-id --name-only --diff-filter=AM -r --root HEAD -- ccHFM/)
            if (( "${#commit_files[@]}" == 0 )) ; then
              echo "No mod files to test."
              exit
            fi

            echo   "## Commit: fresh mod files ##"
            printf "    %q\n" "${commit_files[@]}"

            # the static analysis tool uses these for finer analysis
            scaffolding=(ccHFM/common/cb_types.txt)
            # run static analysis

            vic2-companion --color=always --heartbeat --whitelist --remarks=opinion "${scaffolding[@]}" "${commit_files[@]}"
